-- AlterTable
ALTER TABLE "Aluno" ALTER COLUMN "nome" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "email" SET DATA TYPE VARCHAR(254),
ALTER COLUMN "dataNascimento" SET DATA TYPE DATE,
ALTER COLUMN "fotoUrl" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "fotoPublicId" SET DATA TYPE VARCHAR(200);

-- AlterTable
ALTER TABLE "Curso" ALTER COLUMN "nome" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "instrutor" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "Nota" ALTER COLUMN "descricao" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "valor" SET DATA TYPE DECIMAL(4,2);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "nome" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "email" SET DATA TYPE VARCHAR(254),
ALTER COLUMN "senha" SET DATA TYPE CHAR(60);
